[package]
name = "bmb_recceiver_raspberry_pi"
version = "0.1.0"
authors = ["coffeyrt <coffeyrt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = "0.11"
